# Generated by Django 4.1 on 2022-09-03 17:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(default='', max_length=64)),
                ('jobBody', models.TextField(default='')),
                ('jobCompany', models.CharField(default='', max_length=64)),
                ('jobType', models.CharField(max_length=64, null=True)),
                ('jobLevel', models.CharField(max_length=64, null=True)),
                ('jobIndustry', django_mysql.models.ListCharField(models.CharField(max_length=16), max_length=100, null=True, size=None)),
                ('jobSalaryLow', models.IntegerField(null=True)),
                ('jobSalaryHigh', models.IntegerField(null=True)),
                ('jobSalaryFrequency', models.CharField(max_length=64, null=True)),
                ('jobRemote', models.BooleanField(default=False)),
                ('jobTechnologies', django_mysql.models.ListCharField(models.CharField(max_length=16), max_length=100, null=True, size=None)),
                ('jobLink', models.CharField(default='', max_length=64)),
                ('jobSiteID', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
    ]
