# Generated by Django 4.1 on 2022-09-03 17:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=django_mysql.models.ListCharField(models.CharField(max_length=16), max_length=100, null=True, size=None),
        ),
    ]
